Deployment Summary
==================

Environment: ${environment}
Server Count: ${server_count}

Server Names:
%{ for name in server_names ~}
  - ${name}
%{ endfor ~}

Enabled Features:
%{ for feature in enabled_features ~}
  - ${feature}
%{ endfor ~}

Tags:
%{ for key, value in tags ~}
  ${key}: ${value}
%{ endfor ~}

Generated by Terraform
